### ISSUE TITLE
require error with async

### ISSUE THREAD

**Issue by solnic** [socketry/db-postgres#2]
Hey Samuel! I'm very excited about db gem and the new drivers you've been working on. I'd love to try it out with an SQL builder gem that I recently started working on, unfortunately I've hit this problem:

```
[1] pry(main)> require "db/postgres/connection"
LoadError: cannot load such file -- async/pool/resource
from /Users/solnic/.gem/ruby/2.7.2/gems/db-postgres-0.2.3/lib/db/postgres/connection.rb:23:in `require'
[2] pry(main)> require "async"
=> true
[3] pry(main)> require "async"
=> false
[4] pry(main)> require "db/postgres/connection"
LoadError: cannot load such file -- async/pool/resource
from /Users/solnic/.gem/ruby/2.7.2/gems/db-postgres-0.2.3/lib/db/postgres/connection.rb:23:in `require'
```

Is this expected? Thanks!

**Comment by ioquatix** [comment]
Can you please try v0.2.4 which includes the missing dependency.

**Comment by solnic** [comment]
@ioquatix it worked, thank you!

**Comment by ioquatix** [comment]
Great.
